on: [push]
jobs:
  dotnetpack_nugetpush_job:
    runs-on: ubuntu-latest
    env:
      projectpath: ./dotnet_example.csproj
      buildconfiguration: release
      outputpath: mypkgout
      runid: ${{github.run_id}}
      githubtoken: ${{ secrets.TOKEN }}
      githubnugetpackageregistry: https://nuget.pkg.github.com/sbenzal/index.json

    steps:
     - uses: actions/checkout@v2.3.4
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v1.7.2
       with:
         dotnet-version: '5.0.101'
         
     - name: Restore with dotnet
       run: dotnet restore ${projectpath}
       
     - name: Build with dotnet
       run: dotnet build ${projectpath} --configuration ${buildconfiguration} --version-suffix ${runid} --no-restore
       #run: dotnet build ${projectpath} --configuration ${buildconfiguration} --no-restore

     - name: Pack as nuget with dotnet
       run: dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --versionsuffix ${runid} --no-build --no-restore
       #run: dotnet pack ${projectpath} --configuration ${buildconfiguration} --output ${outputpath} --no-build --no-restore

     - name: Publish Nuget to GitHub registry
       run: dotnet nuget push ${outputpath}/*.nupkg --api-key ${githubtoken} --source ${githubnugetpackageregistry} --skip-duplicate --no-symbols true
